name: Lokia CI/CD (Backend)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-validation:
    runs-on: ubuntu-latest
    
    env:
      PostgreUser: ${{ secrets.POSTGREUSER }}
      PostgrePassword: ${{ secrets.POSTGREPASSWORD }}
      PostgreDB: ${{ secrets.POSTGREDB }}
      PostgrePort: ${{ secrets.POSTGREPORT }}
      PostgreHost: ${{ secrets.POSTGREHOST }}
      PostgreSSLMODE: ${{ secrets.POSTGRESSLMODE }}
      
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      OllamaPort: ${{ secrets.OLLAMAPORT }} 
      OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
      
      TAVILY_KEY_1: ${{ secrets.TAVILY_KEY_1 }}
      TAVILY_KEY_2: ${{ secrets.TAVILY_KEY_2 }}
      TAVILY_KEY_3: ${{ secrets.TAVILY_KEY_3 }}

    steps:
      - name: Recorporer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: backend/go.sum

      - name: Installer les dépendances Go
        run: |
          cd backend
          go mod download

      - name: Vérifier le formatage du code (go fmt)
        run: |
          cd backend
          if [ -n "$(gofmt -l .)" ]; then
            echo "Le code Go n'est pas bien formaté."
            exit 1
          fi

      - name: Compiler le Backend
        run: |
          cd backend
          go build -v ./...

      - name: Lancer les tests unitaires Go
        run: |
          cd backend
          go test -v ./...
