name: Lokia CI (Go & React)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  frontend-validation:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout du code
          uses: actions/checkout@v4
  
        - name: Configuration de Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '25'
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
  
        - name: Installer les dépendances Frontend
          run: |
            cd frontend
            npm ci
  
        - name: Lancer le Build de l'interface React
          run: |
            cd frontend
            npm run build
